name: morphct
channels:
- conda-forge
- pyscf
dependencies:
- blas=*=openblas
- cython=0.29
- ele
- freud
- gsd
- h5py<3.0
- hdf5
- libcint=4
- matplotlib
- numpy
- openbabel
- pip
- pyscf<2.0
- python=3.7
- scipy
- pytest
- pytest-cov
